#!/bin/zsh

local -a args=("$@")
(( $# == 0 )) && args=("$PWD")

if [[ "${VSCODE_INJECTION}" == 1 ]] && (( ! ${args[(I)-n|-r|--new-window|--reuse-window]} )); then
  args=(-r "${args[@]}")
fi

command code "${args[@]}"
