#!/bin/zsh

local -a args=("$@")
(( $# == 0 )) && args=("$PWD")

if [[ "${VSCODE_INJECTION}" == 1 ]] && (( ! ${args[(I)-n|-r|-a|--new-window|--reuse-window|--add]} )); then
  args=(-r "${args[@]}")
fi

command code "${args[@]}"
