#!/bin/zsh

local -a args=("$@")
(( $# == 0 )) && args=("$PWD")

if [[ "${ZED_TERM}" == true ]] && (( ! ${args[(I)-n|-a|-e|-r|--new|--add|--existing|--reuse|--classic]} )); then
  local arg behavior=-a
  for arg in "${args[@]}"; do
    if [[ -d "$arg" ]]; then
      behavior=-r
      break
    fi
  done
  args=("$behavior" "${args[@]}")
fi

command zed "${args[@]}"
