#!/bin/zsh

local -a args=("$@")
(( $# == 0 )) && args=("$PWD")

if [[ "${ZED_TERM}" == true ]] && (( ! ${args[(I)-n|-a|-e|-r|--new|--add|--existing|--reuse|--classic]} )); then
  args=(-a "${args[@]}")
fi

command zed "${args[@]}"
