#!/bin/bash

set -eu

if [ "$*" = -usage ]; then
  echo "open memo root directory in VSCode"
  exit
fi

memodir=$(cat ~/.config/memo/config.toml | grep memodir | sed -e 's/memodir = "\(.*\)"/\1/' -e "s|^~|$HOME|")
code $(dirname $memodir)
