#!/bin/zsh

local -A opts
zparseopts -D -A opts -- d: -duration:=d i -incognito=i

local profile="$1"
if [[ -z "${profile}" ]]; then
  profile="$(aws-vault list --profiles | grep -E "^aws-vault" | cut -c11- | fzf +m)"
fi
[[ -n "${profile}" ]] || return

local login_url
if [[ -n "${opts[(i)-d]}" ]]; then
  login_url="$(aws-vault login "aws-vault.${profile}" --stdout --duration "${opts[-d]}")"
else
  login_url="$(aws-vault login "aws-vault.${profile}" --stdout)"
fi

local aws_vault_status="$?"
[[ "${aws_vault_status}" -ne 0 ]] && return "${aws_vault_status}"

if [[ -n "${opts[(i)-i]}" ]]; then
  open -na 'Microsoft Edge' --args --incognito \
    --user-data-dir="${HOME}/Library/Application Support/Microsoft\ Edge/aws-vault/${profile}" \
    "${login_url}"
else
  open -na 'Microsoft Edge' "${login_url}"
fi
