#!/bin/zsh

local -A opts
zparseopts -A opts -D -M -- q: -query:=q

local dir="$(ghq list -p | sed -e "s|${HOME}/||" | fzf +m -q "${opts[-q]}")"

if [[ -n "${dir}" ]]; then
  echo "${HOME}/${dir}"
fi
