#!/bin/zsh

local -A opts
zparseopts -A opts -D -M -- q: -query:=q r -remotes=r

local git_opts
[[ -n "${opts[(i)-r]}" ]] && git_opts="-r"
eval "git branch --format='%(refname:short)' --sort=-committerdate ${git_opts}" \
  | fzf +m +s -q "${opts[-q]}"
