#!/bin/zsh

unset git_info
typeset -gA git_info

source $(brew --prefix)/etc/bash_completion.d/git-prompt.sh

local git_prompt=$(GIT_PS1_SHOWDIRTYSTATE=1 \
  GIT_PS1_SHOWSTASHSTATE=1 \
  GIT_PS1_SHOWUNTRACKEDFILES=1 \
  GIT_PS1_SHOWUPSTREAM=auto \
  __git_ps1 " (%s)")
git_info[prompt]="%B%F{red}${git_prompt}%f%b"
