#!/bin/zsh

if [[ ! -f Makefile || "$@" != 'help' ]]; then
  command make $@
  return 0
fi

local targets="$(command grep -E '^[A-Za-z0-9_-]+:' Makefile)"

if echo "${targets}" | grep -q -E '^help:'; then
  command make help
  return 0
fi

echo 'targets:'
for target in "${(f)targets}"; do
  echo "  ${fg[cyan]}${target}${reset_color}"
done
