#!/bin/zsh

if [[ ! -f Makefile || "$1" != 'help' ]]; then
  command make $1
  return 0
fi

local targets="$(command grep -E '^[A-Za-z0-9_-]+:' Makefile)"

if echo "${targets}" | grep -q -E '^help:'; then
  command make help
  return 0
fi

echo "targets:"
for target in "${(f)targets}"; do
  echo "  ${fg[cyan]}${target}${reset_color}"
done
