#!/bin/zsh

local git_prompt=$(GIT_PS1_SHOWDIRTYSTATE=1 \
  GIT_PS1_SHOWSTASHSTATE=1 \
  GIT_PS1_SHOWUNTRACKEDFILES=1 \
  GIT_PS1_SHOWUPSTREAM=auto \
  __git_ps1 " (%s)")

PROMPT="
%(3L.%F{yellow}(%L)%f .)%(!.%F{red}%n%f.${SSH_TTY:+"%F{yellow}%n%f"})${SSH_TTY:+"@%F{green}%m%f:"}%F{cyan}%~%f%F{red}${git_prompt}%f${duration_info}
%(1j.%F{blue}*%f .)%(?.%F{green}.%F{red}%? )%(!.#.$)%f "
