#!/bin/zsh

local pane_path="$(tmux display-message -p '#{pane_current_path}')"
local window_id="$(tmux display-message -p '#{window_id}')"

if [[ -z "${pane_path}" || -z "${window_id}" ]]; then
  return 0
fi

local dir
if git -C "${pane_path}" rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  dir="$(git -C "${pane_path}" rev-parse --show-toplevel)"
else
  dir="${pane_path}"
fi

tmux rename-window -t "${window_id}" "$(basename "$(dirname "${dir}")")/$(basename "${dir}")"
